CREATE DATABASE TechnicalAssistance;

USE TechnicalAssistance;

CREATE TABLE CUSTOMER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CODE INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL
);

CREATE TABLE ADDRESS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STREET VARCHAR(60) NOT NULL,
    NUMBER INT NOT NULL,
    COMPLEMENT VARCHAR(50),
    NEIGHBORHOOD VARCHAR(30) NOT NULL,
    CITY VARCHAR(25) NOT NULL,
    STATE VARCHAR(25) NOT NULL,
    ZIPCODE VARCHAR(9) NOT NULL
);

CREATE TABLE PAYMENT_METHOD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE ORDER_STATUS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL
);

ALTER TABLE CUSTOMER
ADD ADDRESS_ID INT;

ALTER TABLE CUSTOMER
ADD FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID);

ALTER TABLE PAYMENT_METHOD
ADD CODE INT NOT NULL;

CREATE TABLE CUSTOMER_ORDER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CODE INT NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PAYMENT_METHOD_ID INT NOT NULL,
    STATUS_ID INT NOT NULL,

    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(ID),
    FOREIGN KEY (STATUS_ID) REFERENCES ORDER_STATUS(ID)
);